# Generated by Django 2.2.28 on 2024-01-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medic_choice',
            field=models.CharField(blank=True, choices=[('t', 'tablet'), ('s', 'syrup')], default='t', help_text='Select the medicne type', max_length=1),
        ),
    ]
