# Generated by Django 2.2.28 on 2024-01-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0003_auto_20240131_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medichoice',
            new_name='status',
        ),
    ]
