# Generated by Django 2.2.28 on 2024-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='First Name', max_length=100)),
                ('lastname', models.CharField(help_text='Last Name', max_length=100)),
            ],
        ),
    ]
